/* AUTO-GENERATED by scripts/build-pedagogical-curriculum.mjs. */
export const EDITORIAL_DUEL_ANSWER_KEY = {
  "editorial-duel-01": "C",
  "editorial-duel-02": "C",
  "editorial-duel-03": "C",
  "editorial-duel-04": "E",
  "editorial-duel-05": "E",
  "editorial-duel-06": "E",
  "editorial-duel-07": "E",
  "editorial-duel-08": "E",
  "editorial-duel-09": "C",
  "editorial-duel-10": "E",
  "editorial-duel-11": "E",
  "editorial-duel-12": "C"
} as const;
export const EDITORIAL_DUEL_QUESTION_SET_VERSION = 'editorial-duel-23090bf61625314a';
