"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.OFFICIAL_SIMULADO_VERSION = exports.OFFICIAL_SIMULADO_ANSWER_KEY = void 0;
/* AUTO-GENERATED by scripts/build-pedagogical-curriculum.mjs. */
exports.OFFICIAL_SIMULADO_ANSWER_KEY = {
    "editorial-sim-01": "C",
    "editorial-sim-02": "C",
    "editorial-sim-03": "C",
    "editorial-sim-04": "C",
    "editorial-sim-05": "B",
    "editorial-sim-06": "E",
    "editorial-sim-07": "E",
    "editorial-sim-08": "E",
    "editorial-sim-09": "D",
    "editorial-sim-10": "E",
    "editorial-sim-11": "E",
    "editorial-sim-12": "C",
    "editorial-sim-13": "A",
    "editorial-sim-14": "E",
    "editorial-sim-15": "E",
    "editorial-sim-16": "C",
    "editorial-sim-17": "B",
    "editorial-sim-18": "D",
    "editorial-sim-19": "E",
    "editorial-sim-20": "D"
};
exports.OFFICIAL_SIMULADO_VERSION = 'editorial-simulado-88ae8bc080baf574';
