/* AUTO-GENERATED by scripts/build-pedagogical-curriculum.mjs. */
import type { DailyTip } from './dailyTips';

export const EDITORIAL_DAILY_TIPS = [
  {
    "id": "tip-mod0-fonetica-e-fonologia",
    "category": "Fonética e Fonologia",
    "rule": "Qual erro deve ser evitado em O Impacto do H Inicial Mudo na Contagem?",
    "explanation": "Esquecer de subtrair o H inicial mudo na contagem de fonemas por não encontrá-lo na lista clássica de dígrafos.",
    "example": "Estratégia de recuperação: Nomeie primeiro o erro; depois reconstrua a regra corretiva.",
    "moduleId": "mod0"
  },
  {
    "id": "tip-mod1-classes-variaveis-e-invariaveis",
    "category": "Classes Variáveis e Invariáveis",
    "rule": "Qual erro deve ser evitado em Pegadinha do Escopo do Sublinhado (Núcleo vs. Locução)?",
    "explanation": "Erro: Classificar o substantivo isolado \"zona\" como invariável ou advérbio por notar que a expressão completa \"na zona rural\" indica lugar. Correção: Analise estritamente o termo sublinhado. Se o sublinhado for apenas zona , trata-se de um substantivo (variável). Apenas se a banca destacar a expressão inteira na zona rural teremos uma locução adverbial (invariável).",
    "example": "Estratégia de recuperação: Nomeie primeiro o erro; depois reconstrua a regra corretiva.",
    "moduleId": "mod1"
  },
  {
    "id": "tip-mod2-preposicoes",
    "category": "Preposições",
    "rule": "Qual erro deve ser evitado em Uso Incorreto de Crase Após Preposições Essenciais?",
    "explanation": "O Erro: Inserir acento grave em expressões como ante à situação ou desde às 8h em redações discursivas e peças jurídicas. Por que ocorre: Tentativa de hipercorreção formal (\"falar bonito\"). Regra Corrigida: As preposições essenciais ante e desde já exercem a função conectiva. O elemento seguinte é apenas o artigo definido feminino ( ante a situação , desde as 8h ). A única preposição essencial com crase facultativa é até ( até a praça / até à praça ).",
    "example": "Estratégia de recuperação: Nomeie primeiro o erro; depois reconstrua a regra corretiva.",
    "moduleId": "mod2"
  },
  {
    "id": "tip-mod3-pronomes-pessoais",
    "category": "Pronomes Pessoais",
    "rule": "Qual erro deve ser evitado em A Armadilha Fônica do Pronome Indefinido \"Alguém\"?",
    "explanation": "NUNCA utilize a palavra \"alguém\" para fazer testes de regência verbal. O falante brasileiro tende a inserir intuitivamente a preposição a antes de alguém por eufonia ( \"estimo a alguém\" , \"satisfaz a alguém\" ), induzindo à escolha errônea do pronome LHE para verbos transitivos diretos. Use sempre \"o menino\".",
    "example": "Estratégia de recuperação: Nomeie primeiro o erro; depois reconstrua a regra corretiva.",
    "moduleId": "mod3"
  },
  {
    "id": "tip-mod4-tempos-e-modos-verbais",
    "category": "Tempos e Modos Verbais",
    "rule": "Qual erro deve ser evitado em Confusão entre Presente do Indicativo e Presente do Subjuntivo em Verbos de 1ª Conjugação (-AR)?",
    "explanation": "A Pegadinha: Verbos de 1ª conjugação trocam a vogal temática a por e no Presente do Subjuntivo. A banca apresenta frases como \"É provável que ele estude amanhã\" e afirma que estude está no Presente do Indicativo por expressar uma ação atual/futura. Como Evitar: Aplique o teste \"De onde saiu?\": Hoje ele estuda ➔ Presente do Indicativo. Que ele estude ➔ Presente do Subjuntivo. Como o texto traz estude , trata-se de Subjuntivo.",
    "example": "Estratégia de recuperação: Nomeie primeiro o erro; depois reconstrua a regra corretiva.",
    "moduleId": "mod4"
  },
  {
    "id": "tip-mod5-transitividade-verbal-fundamentos",
    "category": "Transitividade Verbal - Fundamentos",
    "rule": "Qual erro deve ser evitado em Divergência Doutrinária Específica da Banca FCC?",
    "explanation": "Cenário: Verbos de deslocamento com locativo obrigatório ( ir a , comparecer a , morar em ). Regra Geral (Cebraspe, FGV, Vunesp): Verbo Intransitivo + Adjunto Adverbial de Lugar. Posição Isolada da FCC: Classifica esses verbos como Transitivos Indiretos (VTI) e o termo locativo como Objeto Indireto (teoria dos transitivos circunstanciais).",
    "example": "Estratégia de recuperação: Nomeie primeiro o erro; depois reconstrua a regra corretiva.",
    "moduleId": "mod5"
  },
  {
    "id": "tip-mod6-analise-sintatica-conceitos-iniciais",
    "category": "Análise Sintática - Conceitos Iniciais",
    "rule": "Qual erro deve ser evitado em Confundir Relevância Temática Global com Núcleo Sintático Estrutural?",
    "explanation": "Problema: Concluir intuitivamente que o tema central do texto (ex.: \"inteligência artificial\") deve ser o núcleo do sujeito sintático. Forma Correta: O núcleo sintático é a palavra estrutural determinada regente ( \"expressão\" ), enquanto o tema é apenas o conteúdo do aposto modificador.",
    "example": "Estratégia de recuperação: Nomeie primeiro o erro; depois reconstrua a regra corretiva.",
    "moduleId": "mod6"
  },
  {
    "id": "tip-mod7-periodo-composto-fundamentos",
    "category": "Período Composto - Fundamentos",
    "rule": "Qual erro deve ser evitado em A Pegadinha do \"Seja... Seja\" (Verbo vs. Conjunção de Termos)?",
    "explanation": "Problema: O candidato assume que a palavra seja é sempre a forma conjugada do verbo ser e que sua repetição cria novas orações no período. Forma correta: Constatar se há verbo subordinado após o termo. Em \"seja no contexto escolar, seja em outros contextos\" , o par seja... seja funciona como conjunção alternativa coordenativa ligando termos nominais. Não há verbos novos e não se cria período composto.",
    "example": "Estratégia de recuperação: Nomeie primeiro o erro; depois reconstrua a regra corretiva.",
    "moduleId": "mod7"
  },
  {
    "id": "tip-mod8-sinais-de-pontuacao-visao-geral",
    "category": "Sinais de Pontuação - Visão Geral",
    "rule": "Qual erro deve ser evitado em Armadilha do Adjetivo ou Advérbio Intercalado tomado por Aposto?",
    "explanation": "A banca Cebraspe isola uma palavra ou oração entre duas vírgulas e propõe no item que o termo possui \"função apositiva\", confiando que o candidato associa superficialmente \"termo entre vírgulas = aposto\".",
    "example": "Estratégia de recuperação: Nomeie primeiro o erro; depois reconstrua a regra corretiva.",
    "moduleId": "mod8"
  },
  {
    "id": "tip-mod9-concordancia-verbal-fundamentos",
    "category": "Concordância Verbal - Fundamentos",
    "rule": "Qual erro deve ser evitado em Distanciamento Sintático e Termos Atrativos Plurais Intercalados?",
    "explanation": "Problema: Bancas intercalam longas orações adjetivas ou adjuntos adverbiais plurais entre o sujeito singular e o verbo. Exemplo clássico: \"O acordo [sobre mudanças climáticas aprovado pelos países] pode subsidiar...\" (O candidato lê o plural vizinho países e flexiona erroneamente podem ). Prevenção: Isole os termos intercalados e conecte o verbo diretamente ao substantivo nuclear ( acordo pode ).",
    "example": "Estratégia de recuperação: Nomeie primeiro o erro; depois reconstrua a regra corretiva.",
    "moduleId": "mod9"
  },
  {
    "id": "tip-mod10-regencia-verbal-fundamentos",
    "category": "Regência Verbal - Fundamentos",
    "rule": "Qual é o objetivo central de Regência Verbal - Fundamentos?",
    "explanation": "Estabelecer as bases conceituais, sintáticas e metodológicas do estudo da regência verbal para concursos públicos; dissecar exaustivamente os dois grandes blocos de verbos da língua portuguesa (verbos que alteram a regência com alteração de sentido e verbos que admitem variação de regência mantendo rigorosamente o mesmo significado semântico); fixar o comportamento sintático de verbos pronominais e arcaísmos sintáticos; e aplicar esses modelos na resolução analítica de quest…",
    "example": "Estratégia de recuperação: Recupere o critério decisivo antes de consultar a resposta.",
    "moduleId": "mod10"
  },
  {
    "id": "tip-mod11-coesao-textual-visao-geral",
    "category": "Coesão Textual - Visão Geral",
    "rule": "Qual é o objetivo central de Coesão Textual - Visão Geral?",
    "explanation": "Compreender e definir os princípios normativos e conceituais de Coesão Textual - Visão Geral. Aplicar regras canônicas e procedimentos decisórios de Coesão Textual - Visão Geral na resolução de questões. Analisar o papel de Coesão Textual - Visão Geral no eixo Apoio estrutural e reconhecer armadilhas e variações de bancas.",
    "example": "Estratégia de recuperação: Recupere o critério decisivo antes de consultar a resposta.",
    "moduleId": "mod11"
  },
  {
    "id": "tip-mod12-sentido-proprio-e-figurado",
    "category": "Sentido Próprio e Figurado",
    "rule": "Qual erro deve ser evitado em Achar que o Segundo Sentido Dicionarizado na Polissemia é Figurado?",
    "explanation": "Erro Comum: Julgar que palavras com mais de um significado no dicionário possuem um sentido \"verdadeiro\" e outro \"figurado\". Forma Correta: Vocábulos polissêmicos (como banco , montar , canto ) abrigam múltiplos significados que são todos denotativos e reais. O sentido figurado exige transposição analógica não dicionarizada no plano literal.",
    "example": "Estratégia de recuperação: Nomeie primeiro o erro; depois reconstrua a regra corretiva.",
    "moduleId": "mod12"
  },
  {
    "id": "tip-mod13-recorrencia",
    "category": "Recorrência",
    "rule": "Qual erro deve ser evitado em A Armadilha Fatal da \"Verdade da Vida\"?",
    "explanation": "Problema: Julgar uma assertiva como CERTA porque seu conteúdo coincide com a realidade empírica evidente do cotidiano (ex.: \"a maioria das escolas brasileiras é precária\" ). Consequência: Cometer extrapolação extratextual. Forma correta: Perguntar friamente: \"Onde está escrito isso no texto com todas as letras ou paráfrase direta?\" . Se a resposta for \"não está escrito, mas todo mundo sabe que é verdade\" , marque imediatamente ERRADO.",
    "example": "Estratégia de recuperação: Nomeie primeiro o erro; depois reconstrua a regra corretiva.",
    "moduleId": "mod13"
  },
  {
    "id": "tip-mod14-revisao-ortografia",
    "category": "Revisão · Ortografia",
    "rule": "Qual regra deve ser recuperada na revisão de Ortografia?",
    "explanation": "• Terminados em A(s),E(s),O(s): pá, três, pós",
    "example": "Estratégia de recuperação: Formule a regra e produza um exemplo próprio antes de virar o cartão.",
    "moduleId": "mod14"
  }
] as DailyTip[];
