/* AUTO-GENERATED by scripts/build-pedagogical-curriculum.mjs. */
import { PEDAGOGICAL_KNOWLEDGE_PART_001 } from './pedagogicalKnowledge.part-001.generated';
import { PEDAGOGICAL_KNOWLEDGE_PART_002 } from './pedagogicalKnowledge.part-002.generated';
import { PEDAGOGICAL_KNOWLEDGE_PART_003 } from './pedagogicalKnowledge.part-003.generated';
import { PEDAGOGICAL_KNOWLEDGE_PART_004 } from './pedagogicalKnowledge.part-004.generated';
import { PEDAGOGICAL_KNOWLEDGE_PART_005 } from './pedagogicalKnowledge.part-005.generated';
import { PEDAGOGICAL_KNOWLEDGE_PART_006 } from './pedagogicalKnowledge.part-006.generated';
import { PEDAGOGICAL_KNOWLEDGE_PART_007 } from './pedagogicalKnowledge.part-007.generated';
import { PEDAGOGICAL_KNOWLEDGE_PART_008 } from './pedagogicalKnowledge.part-008.generated';

export const PEDAGOGICAL_KNOWLEDGE_INDEX = [
  ...PEDAGOGICAL_KNOWLEDGE_PART_001,
  ...PEDAGOGICAL_KNOWLEDGE_PART_002,
  ...PEDAGOGICAL_KNOWLEDGE_PART_003,
  ...PEDAGOGICAL_KNOWLEDGE_PART_004,
  ...PEDAGOGICAL_KNOWLEDGE_PART_005,
  ...PEDAGOGICAL_KNOWLEDGE_PART_006,
  ...PEDAGOGICAL_KNOWLEDGE_PART_007,
  ...PEDAGOGICAL_KNOWLEDGE_PART_008,
] as const;
