/* AUTO-GENERATED by scripts/build-pedagogical-curriculum.mjs. */
export const SUVECA_METHOD = {
  "schemaVersion": "1.0.0",
  "methodId": "suveca-analysis-map-v1",
  "name": "Método SuVeCA",
  "equation": "Sujeito + Verbo + Complemento + Adjunto + Predicativo",
  "definition": "A SuVeCA é um mapa de análise para reconstruir as relações sintáticas, e não um molde obrigatório. Em concursos, as frases frequentemente aparecem em ordem inversa, com termos omitidos ou sem sujeito.",
  "authorityNote": "A SuVeCA é a camada metodológica do aplicativo. Ela organiza a aplicação do conteúdo, mas não cria regras gramaticais nem substitui a autoridade normativa do corpus_apostila.",
  "principles": [
    "Su–Ve–C–A–Pred representa funções e relações, não a ordem linear obrigatória da frase.",
    "A análise preserva a ordem em que os termos aparecem e, em paralelo, reconstrói as relações entre eles.",
    "Nenhum bloco é obrigatório: o sujeito pode estar expresso, posposto, oculto, indeterminado ou ser inexistente; complementos, adjuntos e predicativos aparecem conforme a estrutura real.",
    "O verbo ou a locução verbal ancora a predicação, mas a primeira tarefa é delimitar corretamente as orações do período.",
    "Perguntas como quem, o quê, a quem, onde e como são pistas iniciais; a decisão final depende de concordância, regência, constituição, escopo e sentido.",
    "Forma, classe e função não se confundem: a mesma classe pode ocupar funções diferentes, e uma função pode ser realizada por estruturas diferentes.",
    "Quando o fenômeno ultrapassa a oração, a análise sobe de camada: oração, período, texto e discurso."
  ],
  "workflow": [
    {
      "code": "OR",
      "title": "Delimite as orações",
      "instruction": "Localize verbos e locuções, conectores e limites de cada oração antes de classificar termos."
    },
    {
      "code": "VE",
      "title": "Encontre o núcleo verbal",
      "instruction": "Determine predicação, voz, sentido contextual e exigências de regência de cada verbo."
    },
    {
      "code": "SU",
      "title": "Resolva o sujeito",
      "instruction": "Use concordância e sentido para verificar se o sujeito é expresso, posposto, oculto, indeterminado ou inexistente."
    },
    {
      "code": "C",
      "title": "Complete a valência",
      "instruction": "Identifique objetos e demais complementos exigidos pelo verbo ou por um nome, sem confundi-los com circunstâncias."
    },
    {
      "code": "A",
      "title": "Separe os adjuntos",
      "instruction": "Localize circunstâncias e modificadores acessórios, verificando a qual núcleo ou oração cada um se liga."
    },
    {
      "code": "PRED",
      "title": "Teste os predicativos",
      "instruction": "Verifique se uma característica ou estado é atribuído ao sujeito ou ao objeto por intermédio da predicação."
    },
    {
      "code": "MAPA",
      "title": "Reconstrua as relações",
      "instruction": "Registre o padrão na ordem real da frase e explique os vínculos; não reorganize a frase como se a ordem direta fosse obrigatória."
    },
    {
      "code": "PROVA",
      "title": "Aplique o teste do tema",
      "instruction": "Só depois do mapa básico, aplique o critério específico de concordância, regência, pontuação, reescrita, coesão ou interpretação."
    }
  ],
  "components": [
    {
      "code": "Su",
      "name": "Sujeito",
      "question": "Com que termo o verbo concorda e de quem se declara algo?",
      "warning": "Não presuma que o sujeito vem antes do verbo nem que toda oração possui sujeito."
    },
    {
      "code": "Ve",
      "name": "Verbo",
      "question": "Qual é o núcleo da predicação e que relações ele exige neste contexto?",
      "warning": "A transitividade pertence ao emprego contextual, não a uma etiqueta imutável do verbo."
    },
    {
      "code": "C",
      "name": "Complemento",
      "question": "Que termo completa o sentido do verbo ou do nome e qual regência o introduz?",
      "warning": "Preposição, sozinha, não decide entre complemento e adjunto."
    },
    {
      "code": "A",
      "name": "Adjunto",
      "question": "Que circunstância ou modificação acessória incide sobre o verbo, o nome ou a oração?",
      "warning": "Deslocamento e extensão alteram pontuação e escopo, mas não transformam automaticamente a função."
    },
    {
      "code": "Pred",
      "name": "Predicativo",
      "question": "Que estado ou característica é atribuído ao sujeito ou ao objeto?",
      "warning": "Predicativo não exige apenas verbo de ligação e pode coexistir com verbos transitivos."
    }
  ],
  "patterns": [
    {
      "name": "Ordem direta",
      "surface": "Su + Ve + C + A",
      "example": "Os servidores entregaram o relatório ontem."
    },
    {
      "name": "Ordem inversa",
      "surface": "A + Ve + Su",
      "example": "Ontem chegaram os fiscais."
    },
    {
      "name": "Sujeito oculto",
      "surface": "(Su) + Ve + C",
      "example": "Comprei um livro."
    },
    {
      "name": "Oração sem sujeito",
      "surface": "Ve + C + A",
      "example": "Há vagas aqui."
    },
    {
      "name": "Predicativo",
      "surface": "Su + Ve + Pred",
      "example": "Maria parece cansada."
    }
  ],
  "lessonConnections": {
    "A00": {
      "level": "support",
      "label": "Aplicação pontual",
      "summary": "Ortografia e fonologia não devem ser forçadas para dentro da SuVeCA. Use o mapa somente quando a grafia dos porquês ou outra decisão depender da função e da relação entre termos.",
      "steps": [
        "Resolva primeiro a forma gráfica ou sonora pela regra própria do tema.",
        "Quando houver dependência sintática, delimite a oração e identifique a função do termo.",
        "Não use a posição linear da palavra como único critério."
      ],
      "limits": [
        "A SuVeCA não decide, por si só, separação silábica, acentuação ou emprego do hífen."
      ]
    },
    "A01": {
      "level": "strong",
      "label": "Ponte entre classe e função",
      "summary": "Use a SuVeCA para observar onde cada classe atua na oração, sem confundir classificação morfológica com função sintática.",
      "steps": [
        "Identifique a classe pela forma e pelo comportamento contextual.",
        "Localize o núcleo a que a palavra se liga.",
        "Só então registre sua função no mapa da oração."
      ],
      "limits": [
        "Uma classe não corresponde automaticamente a uma única função sintática."
      ]
    },
    "A02": {
      "level": "strong",
      "label": "Aplicação central",
      "summary": "Reconstrua a SuVeCA de cada oração e só depois determine o papel da preposição ou a relação lógico-semântica criada pela conjunção.",
      "steps": [
        "Delimite os segmentos conectados.",
        "Monte o mapa interno de cada oração.",
        "Classifique o conector pela relação efetivamente construída."
      ],
      "limits": [
        "A forma isolada do conector não determina seu valor no contexto."
      ]
    },
    "A03": {
      "level": "central",
      "label": "Aplicação central",
      "summary": "Posicione o pronome no mapa para separar classe, função, referente e regência; em relativos, reconstrua a lacuna dentro da oração subordinada.",
      "steps": [
        "Identifique o referente ou antecedente.",
        "Recoloque o antecedente na oração do relativo para descobrir a função.",
        "Verifique a regência e, depois, a colocação pronominal."
      ],
      "limits": [
        "Proximidade gráfica não garante antecedente nem função."
      ]
    },
    "A04": {
      "level": "strong",
      "label": "Verbo como âncora",
      "summary": "O verbo é o eixo da SuVeCA: modo, tempo, voz, correlação e formas nominais devem ser interpretados dentro da predicação e do período.",
      "steps": [
        "Localize verbos e locuções.",
        "Separe forma verbal, valor temporal-modal e função no período.",
        "Relacione cada verbo ao sujeito e aos termos que ele organiza."
      ],
      "limits": [
        "A forma verbal isolada não basta para determinar seu valor discursivo."
      ]
    },
    "A05": {
      "level": "central",
      "label": "Núcleo operacional da SuVeCA",
      "summary": "Transitividade, complementos, vozes e predicação são resolvidos reconstruindo as relações que partem do verbo em cada emprego concreto.",
      "steps": [
        "Determine o sentido contextual do verbo.",
        "Identifique sujeito, complementos exigidos e adjuntos.",
        "Teste voz, partícula se e predicativos sem depender da ordem da frase."
      ],
      "limits": [
        "Não memorize transitividade como propriedade imutável do verbo."
      ]
    },
    "A06": {
      "level": "central",
      "label": "Mapa completo da oração",
      "summary": "Esta aula explicita o centro do método: delimitar a oração, ancorar a análise no verbo e reconstruir Sujeito, Complementos, Adjuntos e Predicativos.",
      "steps": [
        "Preserve a ordem superficial da frase.",
        "Monte as relações Su–Ve–C–A–Pred e registre ausências ou elipses.",
        "Use concordância, regência, constituição e sentido para validar cada função."
      ],
      "limits": [
        "Su–Ve–C–A–Pred não é uma sequência obrigatória nem exige que todos os blocos apareçam."
      ]
    },
    "A07": {
      "level": "central",
      "label": "Uma SuVeCA por oração",
      "summary": "No período composto, construa uma SuVeCA para cada oração e depois represente a relação de coordenação, subordinação ou encaixe entre elas.",
      "steps": [
        "Conte e delimite as orações pelos núcleos verbais.",
        "Reconstrua o mapa interno de cada oração.",
        "Determine a função ou a relação semântica da oração no período."
      ],
      "limits": [
        "Uma única linha Su–Ve–C–A não representa adequadamente todo período composto."
      ]
    },
    "A08": {
      "level": "central",
      "label": "Sintaxe antes da pontuação",
      "summary": "Use a SuVeCA para enxergar sujeito, verbo, complementos, adjuntos, termos intercalados e limites oracionais antes de decidir a pontuação.",
      "steps": [
        "Delimite a estrutura sem se orientar primeiro pelas vírgulas existentes.",
        "Identifique função, deslocamento, intercalação e escopo.",
        "Aplique a regra de pontuação à relação reconstruída."
      ],
      "limits": [
        "Pausa de leitura não substitui análise sintática."
      ]
    },
    "A09": {
      "level": "central",
      "label": "Concordância guiada pelo mapa",
      "summary": "Reconstrua o vínculo entre verbo e núcleo do sujeito ou entre nome e seus determinantes para impedir que distância e ordem inversa enganem a concordância.",
      "steps": [
        "Localize o verbo ou nome controlado.",
        "Encontre o núcleo controlador, ainda que posposto ou distante.",
        "Aplique a regra geral e depois verifique o caso especial."
      ],
      "limits": [
        "O termo mais próximo nem sempre controla a concordância."
      ]
    },
    "A10": {
      "level": "central",
      "label": "Regência e crase no mapa",
      "summary": "Parta do sentido contextual do verbo ou nome, identifique o termo regido e só então decida preposição, pronome relativo ou possibilidade de crase.",
      "steps": [
        "Determine o regente e sua acepção.",
        "Localize complemento e preposição exigida.",
        "Na crase, teste separadamente a exigência do a e a admissão do artigo."
      ],
      "limits": [
        "Não decida regência ou crase pela aparência isolada do termo posterior."
      ]
    },
    "A11": {
      "level": "strong",
      "label": "Relações entre mapas",
      "summary": "Use a SuVeCA para rastrear referentes e relações entre orações; depois suba ao texto para avaliar coesão, coerência e preservação de sentido.",
      "steps": [
        "Reconstrua os participantes e relações de cada oração relevante.",
        "Acompanhe retomadas, substituições e conectores entre os mapas.",
        "Confirme o efeito no texto completo."
      ],
      "limits": [
        "Coesão e coerência não se esgotam na estrutura de uma oração isolada."
      ]
    },
    "A12": {
      "level": "support",
      "label": "Mapa para comparar leituras",
      "summary": "Em ambiguidade e polissemia, construa um mapa para cada leitura possível e explicite o que muda em sentido, função, encaixe ou referente.",
      "steps": [
        "Localize o elemento que admite leituras concorrentes.",
        "Reconstrua as relações de cada interpretação.",
        "Use o contexto para manter ou eliminar leituras."
      ],
      "limits": [
        "Relações lexicais e figuras de linguagem também exigem análise semântica e discursiva."
      ]
    },
    "A13": {
      "level": "support",
      "label": "Da oração ao texto",
      "summary": "A SuVeCA ajuda a reconstruir quem faz o quê, a quem, em que circunstância e com que caracterização; a interpretação final depende também de inferência, gênero, finalidade e discurso.",
      "steps": [
        "Mapeie as relações sintáticas decisivas do trecho.",
        "Conecte participantes, ações, estados e circunstâncias ao longo do texto.",
        "Suba ao plano argumentativo e discursivo antes de concluir."
      ],
      "limits": [
        "O mapa da oração apoia, mas não substitui, a leitura global do texto."
      ]
    },
    "A14": {
      "level": "review",
      "label": "Revisão transversal",
      "summary": "Use o mapa SuVeCA como protocolo de recuperação: identifique em cada questão se a decisão pertence à forma, à classe, à oração, ao período ou ao texto.",
      "steps": [
        "Nomeie a camada linguística cobrada.",
        "Quando houver estrutura sintática, reconstrua Su–Ve–C–A–Pred sem impor ordem.",
        "Aplique a regra específica e justifique a decisão."
      ],
      "limits": [
        "Nem toda questão de língua portuguesa é resolvida apenas pela análise sintática."
      ]
    }
  },
  "groupTaxonomy": {
    "central": {
      "label": "Método central",
      "description": "A reconstrução SuVeCA é o caminho principal para compreender, aplicar e justificar o conteúdo.",
      "steps": [
        "Delimite as orações e preserve a ordem real do enunciado.",
        "Reconstrua Sujeito, Verbo, Complementos, Adjuntos e Predicativos, registrando ausências, elipses e encaixes.",
        "Aplique a regra específica do tema às relações reconstruídas e justifique a resposta."
      ],
      "limits": [
        "O mapa representa relações sintáticas; não impõe ordem direta nem exige que todos os componentes estejam expressos."
      ]
    },
    "strong": {
      "label": "Conexão forte",
      "description": "A SuVeCA organiza uma parte decisiva da análise, em conjunto com a camada própria do tema.",
      "steps": [
        "Reconstrua apenas as relações sintáticas relevantes para a decisão.",
        "Acrescente o critério próprio do tema — morfológico, semântico, coesivo ou discursivo.",
        "Confirme que estrutura e contexto sustentam a mesma conclusão."
      ],
      "limits": [
        "A análise sintática é necessária, mas não substitui a regra específica desta matéria."
      ]
    },
    "support": {
      "label": "Apoio estrutural",
      "description": "A SuVeCA funciona como instrumento de diagnóstico, contraste ou organização; a regra decisiva pertence a outra camada linguística.",
      "steps": [
        "Identifique primeiro a camada linguística efetivamente cobrada.",
        "Use o mapa SuVeCA somente nos trechos em que função, referente, escopo ou encaixe sejam relevantes.",
        "Conclua pela regra própria do tema e explicite o limite da análise sintática."
      ],
      "limits": [
        "Não transforme uma pista sintática em explicação completa de um fenômeno morfológico, semântico ou textual."
      ]
    },
    "indirect": {
      "label": "Apoio indireto",
      "description": "A SuVeCA pode esclarecer exemplos ou efeitos contextuais, mas não é o procedimento normal de resolução.",
      "steps": [
        "Resolva o fenômeno pela regra própria da matéria.",
        "Se houver uma oração relevante, use a SuVeCA apenas para localizar a forma ou o efeito no contexto.",
        "Mantenha separadas a justificativa principal e a observação sintática auxiliar."
      ],
      "limits": [
        "Aplicar o mapa a todos os casos deste grupo criaria uma relação artificial com a sintaxe."
      ]
    },
    "outside_core": {
      "label": "Camada própria, fora do núcleo SuVeCA",
      "description": "O conteúdo possui método de aprendizagem próprio e não deve ser convertido em análise SuVeCA.",
      "steps": [
        "Aplique diretamente a regra fonológica, ortográfica, lexical ou discursiva pertinente.",
        "Use frases completas como contexto de aplicação, sem obrigar sua decomposição sintática.",
        "Recorra à SuVeCA apenas se uma questão específica introduzir uma dependência funcional real."
      ],
      "limits": [
        "A SuVeCA não é fonte da regra deste grupo e sua ausência na resolução pode ser pedagogicamente correta."
      ]
    },
    "review": {
      "label": "Revisão transversal",
      "description": "A SuVeCA é recuperada conforme a camada linguística revisada.",
      "steps": [
        "Identifique se a questão pertence à forma, à classe, à oração, ao período ou ao texto.",
        "Reconstrua o mapa SuVeCA somente quando houver uma decisão sintática relevante.",
        "Aplique a regra específica e justifique por que o método é central, auxiliar ou dispensável naquele caso."
      ],
      "limits": [
        "Uma revisão geral não transforma todos os conteúdos de língua portuguesa em sintaxe."
      ]
    }
  },
  "groupConnections": {
    "A00/G01": {
      "level": "outside_core",
      "label": "Camada própria, fora do núcleo SuVeCA",
      "summary": "Fonemas, grafemas, dígrafos e encontros vocálicos são decididos pela camada fonético-fonológica; a estrutura SuVeCA não produz essas classificações.",
      "editorialSourceId": "SUVECA-A00-G01",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A00/G02": {
      "level": "outside_core",
      "label": "Camada própria, fora do núcleo SuVeCA",
      "summary": "Divisão, estrutura e classificação silábicas obedecem a critérios fonológicos próprios, independentemente das funções Su, Ve, C, A e Pred.",
      "editorialSourceId": "SUVECA-A00-G02",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A00/G03": {
      "level": "outside_core",
      "label": "Camada própria, fora do núcleo SuVeCA",
      "summary": "As questões de sílaba devem ser resolvidas pelos testes fonológicos do tema; uma oração pode fornecer contexto, mas não o critério decisivo.",
      "editorialSourceId": "SUVECA-A00-G03",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A00/G04": {
      "level": "indirect",
      "label": "Apoio indireto",
      "summary": "A acentuação é regida por tonicidade e estrutura silábica. A SuVeCA auxilia apenas em casos contextuais, como formas verbais ligadas a pronomes enclíticos.",
      "editorialSourceId": "SUVECA-A00-G04",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "editorial_baseline_retained_after_review"
    },
    "A00/G05": {
      "level": "outside_core",
      "label": "Camada própria, fora do núcleo SuVeCA",
      "summary": "O emprego do hífen depende de regras ortográficas, prefixos e constituintes morfológicos; não deve ser deduzido do mapa sintático.",
      "editorialSourceId": "SUVECA-A00-G05",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A00/G06": {
      "level": "outside_core",
      "label": "Camada própria, fora do núcleo SuVeCA",
      "summary": "As questões de hífen exigem reconhecer a formação da palavra e aplicar a norma ortográfica, sem converter o procedimento em análise oracional.",
      "editorialSourceId": "SUVECA-A00-G06",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A00/G07": {
      "level": "strong",
      "label": "Conexão forte",
      "summary": "Nos porquês, a reconstrução da oração distingue pronome relativo ou interrogativo, conjunção integrante, causa, explicação e finalidade; tonicidade e posição gráfica completam a decisão.",
      "editorialSourceId": "SUVECA-A00-G07",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A01/G01": {
      "level": "support",
      "label": "Apoio estrutural",
      "summary": "Variabilidade e invariabilidade são propriedades morfológicas. O mapa ajuda a mostrar como cada classe realiza funções diferentes, sem identificar classe e função.",
      "editorialSourceId": "SUVECA-A01-G01",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A01/G02": {
      "level": "strong",
      "label": "Conexão forte",
      "summary": "O emprego das classes fica mais claro quando a palavra é ligada ao núcleo e à função que exerce como Su, C, A, Pred ou elemento interno de um sintagma.",
      "editorialSourceId": "SUVECA-A01-G02",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A01/G03": {
      "level": "strong",
      "label": "Conexão forte",
      "summary": "A SuVeCA localiza o advérbio ou a locução como modificador do verbo, do adjetivo, de outro advérbio ou da oração e ajuda a separar valor adverbial de emprego adjetivo.",
      "editorialSourceId": "SUVECA-A01-G03",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A01/G04": {
      "level": "support",
      "label": "Apoio estrutural",
      "summary": "O artigo é reconhecido morfologicamente e observado dentro do sintagma nominal; a SuVeCA mostra a função do conjunto, não transforma o artigo em componente autônomo do mapa.",
      "editorialSourceId": "SUVECA-A01-G04",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A01/G05": {
      "level": "indirect",
      "label": "Apoio indireto",
      "summary": "Numerais podem integrar núcleos e modificadores do mapa, enquanto interjeições normalmente permanecem fora da oração; o contraste entre integração e autonomia é o ganho da SuVeCA.",
      "editorialSourceId": "SUVECA-A01-G05",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A02/G01": {
      "level": "strong",
      "label": "Conexão forte",
      "summary": "A preposição é interpretada pela relação que introduz: pode completar verbo ou nome em C, ou acrescentar valor nocional em A. A regência e o sentido confirmam a função.",
      "editorialSourceId": "SUVECA-A02-G01",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A02/G02": {
      "level": "strong",
      "label": "Conexão forte",
      "summary": "Monte o mapa interno das orações coordenadas e, em seguida, classifique a relação aditiva, adversativa, alternativa, conclusiva ou explicativa criada entre elas.",
      "editorialSourceId": "SUVECA-A02-G02",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A02/G03": {
      "level": "strong",
      "label": "Conexão forte",
      "summary": "A SuVeCA delimita e organiza as orações; a semântica do conector determina causa, condição, concessão, consequência, finalidade, comparação ou outro valor subordinativo.",
      "editorialSourceId": "SUVECA-A02-G03",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A02/G04": {
      "level": "strong",
      "label": "Conexão forte",
      "summary": "Os valores de “e” e “pois” só são definidos depois de reconstruir os segmentos conectados, sua posição e a relação lógico-discursiva efetivamente construída.",
      "editorialSourceId": "SUVECA-A02-G04",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A02/G05": {
      "level": "strong",
      "label": "Conexão forte",
      "summary": "Os diferentes empregos de “como” e de outros conectores exigem uma SuVeCA por oração e uma segunda análise para a relação semântica entre os mapas.",
      "editorialSourceId": "SUVECA-A02-G05",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A03/G01": {
      "level": "central",
      "label": "Método central",
      "summary": "A função do pronome pessoal como sujeito ou complemento nasce de sua posição relacional no mapa, e a regência do verbo decide entre formas como o, a e lhe.",
      "editorialSourceId": "SUVECA-A03-G01",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A03/G02": {
      "level": "central",
      "label": "Método central",
      "summary": "Nas questões de pronomes pessoais, reconstrua verbo, sujeito e complementos antes de escolher a forma pronominal ou julgar uma substituição.",
      "editorialSourceId": "SUVECA-A03-G02",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "editorial_baseline_retained_after_review"
    },
    "A03/G03": {
      "level": "strong",
      "label": "Conexão forte",
      "summary": "Possessivos, indefinidos e interrogativos combinam morfologia, função e referenciação; a SuVeCA localiza o papel sintático, enquanto o contexto resolve referente e valor.",
      "editorialSourceId": "SUVECA-A03-G03",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A03/G04": {
      "level": "strong",
      "label": "Conexão forte",
      "summary": "Demonstrativos exigem rastreamento contextual, e relativos exigem reconstruir a lacuna na oração subordinada; o mapa liga referente e função sem confundi-los.",
      "editorialSourceId": "SUVECA-A03-G04",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A03/G05": {
      "level": "central",
      "label": "Método central",
      "summary": "Recoloque o antecedente na oração relativa, descubra a função deixada pela lacuna e aplique a regência para selecionar que, quem, onde, aonde, donde, cujo ou formas preposicionadas.",
      "editorialSourceId": "SUVECA-A03-G05",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "editorial_baseline_retained_after_review"
    },
    "A03/G06": {
      "level": "central",
      "label": "Método central",
      "summary": "Regência e reescrita de relativos são resolvidas pela dupla ligação: função dentro da subordinada e retomada do antecedente no período.",
      "editorialSourceId": "SUVECA-A03-G06",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "editorial_baseline_retained_after_review"
    },
    "A03/G07": {
      "level": "central",
      "label": "Método central",
      "summary": "A colocação dos pronomes átonos parte da locução ou forma verbal, dos limites da oração e dos fatores de atração, preservando a função do pronome no mapa.",
      "editorialSourceId": "SUVECA-A03-G07",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "editorial_baseline_retained_after_review"
    },
    "A03/G08": {
      "level": "central",
      "label": "Método central",
      "summary": "Nas questões de colocação, delimite a oração, identifique verbo e pronome, teste atração, início oracional e locuções, e só então julgue próclise, mesóclise ou ênclise.",
      "editorialSourceId": "SUVECA-A03-G08",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "editorial_baseline_retained_after_review"
    },
    "A04/G01": {
      "level": "central",
      "label": "Método central",
      "summary": "Tempos e modos são estudados a partir do verbo que ancora cada oração e das relações temporais, modais e aspectuais que sua forma constrói no período.",
      "editorialSourceId": "SUVECA-A04-G01",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "editorial_baseline_retained_after_review"
    },
    "A04/G02": {
      "level": "central",
      "label": "Método central",
      "summary": "O mapa localiza o verbo e seus participantes; a camada semântico-discursiva determina hipótese, certeza, ordem, possibilidade, habitualidade e demais valores contextuais.",
      "editorialSourceId": "SUVECA-A04-G02",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "editorial_baseline_retained_after_review"
    },
    "A04/G03": {
      "level": "support",
      "label": "Apoio estrutural",
      "summary": "Desinências verbais são analisadas morfologicamente. A SuVeCA fornece o contexto de concordância e permite relacionar marcas de pessoa, número, tempo e modo ao sujeito e à predicação.",
      "editorialSourceId": "SUVECA-A04-G03",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A04/G04": {
      "level": "central",
      "label": "Método central",
      "summary": "Infinitivo, gerúndio e particípio precisam ser localizados na predicação para distinguir locução, oração reduzida, valor nominal e relação com sujeitos, complementos ou predicativos.",
      "editorialSourceId": "SUVECA-A04-G04",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "editorial_baseline_retained_after_review"
    },
    "A04/G05": {
      "level": "indirect",
      "label": "Apoio indireto",
      "summary": "Os paradigmas de verbos irregulares exigem aprendizagem morfológica própria; a SuVeCA apenas mostra em que oração, pessoa e relação a forma conjugada está sendo usada.",
      "editorialSourceId": "SUVECA-A04-G05",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "editorial_baseline_retained_after_review"
    },
    "A04/G06": {
      "level": "indirect",
      "label": "Apoio indireto",
      "summary": "Questões de conjugação irregular são resolvidas pelo paradigma e pelas marcas flexionais, com apoio contextual do sujeito e do valor verbal quando necessário.",
      "editorialSourceId": "SUVECA-A04-G06",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "editorial_baseline_retained_after_review"
    },
    "A04/G07": {
      "level": "indirect",
      "label": "Apoio indireto",
      "summary": "Falsos amigos e verbos de difícil conjugação pertencem principalmente à morfologia verbal; o mapa impede apenas que contexto sintático e forma flexionada sejam confundidos.",
      "editorialSourceId": "SUVECA-A04-G07",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A04/G08": {
      "level": "indirect",
      "label": "Apoio indireto",
      "summary": "Verbos em -ear, -iar e defectivos exigem regras de formação e disponibilidade de formas; a SuVeCA ajuda a verificar pessoa, sujeito e emprego, mas não gera o paradigma.",
      "editorialSourceId": "SUVECA-A04-G08",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A04/G09": {
      "level": "central",
      "label": "Método central",
      "summary": "A correlação verbal é reconstruída entre as orações: identifique os verbos, seus valores e a relação temporal-modal que torna a combinação coerente.",
      "editorialSourceId": "SUVECA-A04-G09",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "editorial_baseline_retained_after_review"
    },
    "A05/G01": {
      "level": "central",
      "label": "Método central",
      "summary": "A valência do verbo em seu sentido contextual determina quais complementos integram C e quais circunstâncias permanecem em A.",
      "editorialSourceId": "SUVECA-A05-G01",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A05/G02": {
      "level": "central",
      "label": "Método central",
      "summary": "Nas questões de transitividade, reconstrua o mapa completo e teste regência, indispensabilidade e sentido, sem atribuir ao verbo uma etiqueta fixa.",
      "editorialSourceId": "SUVECA-A05-G02",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A05/G03": {
      "level": "central",
      "label": "Método central",
      "summary": "Objetos, complementos e construções pleonásticas são identificados pelas relações de completude, regência, retomada e ênfase que se ligam ao verbo ou ao nome.",
      "editorialSourceId": "SUVECA-A05-G03",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A05/G04": {
      "level": "central",
      "label": "Método central",
      "summary": "As vozes verbais redistribuem sujeito, complemento e agente; compare os mapas para compreender a mudança estrutural sem pressupor ordem direta.",
      "editorialSourceId": "SUVECA-A05-G04",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A05/G05": {
      "level": "central",
      "label": "Método central",
      "summary": "Nas questões de voz, verifique transitividade, papel do “se”, sujeito paciente, concordância e agente antes de aceitar qualquer classificação.",
      "editorialSourceId": "SUVECA-A05-G05",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A05/G06": {
      "level": "central",
      "label": "Método central",
      "summary": "A reescrita de voz é validada pela preservação dos participantes e pela redistribuição correta de Su, Ve, C e agente da passiva.",
      "editorialSourceId": "SUVECA-A05-G06",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A05/G07": {
      "level": "central",
      "label": "Método central",
      "summary": "Compare origem e reescrita por mapas relacionais, verificando concordância, tempo, regência e papéis semânticos em cada transformação de voz.",
      "editorialSourceId": "SUVECA-A05-G07",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A05/G08": {
      "level": "central",
      "label": "Método central",
      "summary": "Reescritas complexas exigem reconstruir cada oração e confirmar que participantes, foco, relações e correção gramatical foram preservados.",
      "editorialSourceId": "SUVECA-A05-G08",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A05/G09": {
      "level": "central",
      "label": "Método central",
      "summary": "A etapa final de reescrita consolida o uso do mapa para comparar estruturas superficiais diferentes que mantêm, alteram ou apagam relações sintáticas.",
      "editorialSourceId": "SUVECA-A05-G09",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A05/G10": {
      "level": "central",
      "label": "Método central",
      "summary": "Verbos impessoais exigem registrar sujeito inexistente; nas locuções, o auxiliar carrega flexão e pessoalidade conforme a relação com o verbo principal.",
      "editorialSourceId": "SUVECA-A05-G10",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A05/G11": {
      "level": "central",
      "label": "Método central",
      "summary": "As questões de impessoalidade e auxiliares são resolvidas delimitando a locução, identificando o principal e testando se há sujeito capaz de controlar a concordância.",
      "editorialSourceId": "SUVECA-A05-G11",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A05/G12": {
      "level": "central",
      "label": "Método central",
      "summary": "Nos verbos pronominais, determine se o pronome integra o verbo, realiza complemento, marca voz ou produz outro efeito a partir da valência e do mapa contextual.",
      "editorialSourceId": "SUVECA-A05-G12",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "editorial_baseline_retained_after_review"
    },
    "A06/G01": {
      "level": "central",
      "label": "Método central",
      "summary": "Esta unidade introduz diretamente a SuVeCA como mapa relacional: funções, constituintes e ordem superficial são distinguidos desde o início.",
      "editorialSourceId": "SUVECA-A06-G01",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A06/G02": {
      "level": "central",
      "label": "Método central",
      "summary": "O sujeito é reconstruído pela concordância e pelo sentido, podendo ser anteposto, posposto, oculto, indeterminado ou inexistente.",
      "editorialSourceId": "SUVECA-A06-G02",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A06/G03": {
      "level": "central",
      "label": "Método central",
      "summary": "Predicação verbal e tipos de predicado organizam Ve, complementos e predicativos e mostram que a configuração real depende das relações, não de uma fórmula linear.",
      "editorialSourceId": "SUVECA-A06-G03",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A06/G04": {
      "level": "central",
      "label": "Método central",
      "summary": "Objetos e transitividade materializam a conexão Ve → C, decidida pelo sentido e pela regência de cada emprego verbal.",
      "editorialSourceId": "SUVECA-A06-G04",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A06/G05": {
      "level": "central",
      "label": "Método central",
      "summary": "Complemento nominal e agente da passiva ampliam o mapa para relações ligadas a nomes e à voz passiva, evitando classificações baseadas apenas na preposição.",
      "editorialSourceId": "SUVECA-A06-G05",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "editorial_baseline_retained_after_review"
    },
    "A06/G06": {
      "level": "strong",
      "label": "Conexão forte",
      "summary": "Vocativo e aposto são registrados ao redor do núcleo SuVeCA: um é termo independente de chamamento, o outro explica ou especifica um referente da estrutura.",
      "editorialSourceId": "SUVECA-A06-G06",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A06/G07": {
      "level": "central",
      "label": "Método central",
      "summary": "Adjuntos adverbiais e adnominais são conectados ao verbo, ao nome ou à oração que modificam, com atenção a deslocamento, escopo e pontuação.",
      "editorialSourceId": "SUVECA-A06-G07",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A06/G08": {
      "level": "central",
      "label": "Método central",
      "summary": "Predicativo e adjunto adnominal são separados pela relação de atribuição construída na predicação, não pela simples proximidade do adjetivo ao substantivo.",
      "editorialSourceId": "SUVECA-A06-G08",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A07/G01": {
      "level": "central",
      "label": "Método central",
      "summary": "O período composto exige delimitar os núcleos verbais, montar uma SuVeCA por oração e representar depois as relações entre elas.",
      "editorialSourceId": "SUVECA-A07-G01",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "editorial_baseline_retained_after_review"
    },
    "A07/G02": {
      "level": "central",
      "label": "Método central",
      "summary": "Nas coordenadas, cada oração mantém mapa próprio e a conjunção acrescenta a relação semântica que articula estruturas sintaticamente independentes.",
      "editorialSourceId": "SUVECA-A07-G02",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "editorial_baseline_retained_after_review"
    },
    "A07/G03": {
      "level": "central",
      "label": "Método central",
      "summary": "Orações substantivas ocupam posições de Su, C ou outras funções; adjetivas ligam-se a um nome. O mapa torna visível o encaixe de cada subordinada.",
      "editorialSourceId": "SUVECA-A07-G03",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "editorial_baseline_retained_after_review"
    },
    "A07/G04": {
      "level": "central",
      "label": "Método central",
      "summary": "Orações adverbiais funcionam como A da oração principal, mas seu valor de causa, condição, concessão ou outro depende do conector e do contexto.",
      "editorialSourceId": "SUVECA-A07-G04",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "editorial_baseline_retained_after_review"
    },
    "A07/G05": {
      "level": "central",
      "label": "Método central",
      "summary": "Orações reduzidas são delimitadas pelas formas nominais e encaixadas no mapa conforme a função que exercem no período.",
      "editorialSourceId": "SUVECA-A07-G05",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "editorial_baseline_retained_after_review"
    },
    "A07/G06": {
      "level": "central",
      "label": "Método central",
      "summary": "Nas questões de reduzidas, reconstrua o verbo implícito ou desenvolvido, o sujeito e a função da oração antes de classificá-la.",
      "editorialSourceId": "SUVECA-A07-G06",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "editorial_baseline_retained_after_review"
    },
    "A07/G07": {
      "level": "central",
      "label": "Método central",
      "summary": "Revisão e reescrita de reduzidas usam mapas paralelos para verificar se desenvolvimento, conectivo, tempo e relação sintática foram preservados.",
      "editorialSourceId": "SUVECA-A07-G07",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "editorial_baseline_retained_after_review"
    },
    "A07/G08": {
      "level": "central",
      "label": "Método central",
      "summary": "Desenvolver uma oração reduzida é explicitar conectivo e forma verbal sem alterar seu encaixe funcional nem as relações com a oração principal.",
      "editorialSourceId": "SUVECA-A07-G08",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "editorial_baseline_retained_after_review"
    },
    "A07/G09": {
      "level": "central",
      "label": "Método central",
      "summary": "A função de “que” é decidida delimitando as orações, identificando antecedente ou regente e verificando a posição funcional ocupada no mapa.",
      "editorialSourceId": "SUVECA-A07-G09",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "editorial_baseline_retained_after_review"
    },
    "A07/G10": {
      "level": "central",
      "label": "Método central",
      "summary": "A função de “se” depende da transitividade, voz, sujeito e completude do verbo; a classificação emerge da reconstrução da oração.",
      "editorialSourceId": "SUVECA-A07-G10",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "editorial_baseline_retained_after_review"
    },
    "A08/G01": {
      "level": "central",
      "label": "Método central",
      "summary": "A visão geral dos sinais combina estrutura, semântica e convenções gráficas; a SuVeCA organiza limites e relações, mas nem todo sinal é puramente sintático.",
      "editorialSourceId": "SUVECA-A08-G01",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A08/G02": {
      "level": "central",
      "label": "Método central",
      "summary": "A vírgula é decidida depois de identificar Su, Ve, C, A, termos intercalados e limites oracionais, nunca apenas pela pausa percebida.",
      "editorialSourceId": "SUVECA-A08-G02",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "editorial_baseline_retained_after_review"
    },
    "A08/G03": {
      "level": "central",
      "label": "Método central",
      "summary": "Casos avançados de vírgula exigem comparar posição canônica, deslocamento, intercalação, coordenação, subordinação e mudança de sentido.",
      "editorialSourceId": "SUVECA-A08-G03",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "editorial_baseline_retained_after_review"
    },
    "A08/G04": {
      "level": "strong",
      "label": "Conexão forte",
      "summary": "Ponto e vírgula e dois-pontos dependem da relação entre segmentos; aspas também envolvem citação, destaque e sentido, exigindo camada discursiva além do mapa.",
      "editorialSourceId": "SUVECA-A08-G04",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A08/G05": {
      "level": "support",
      "label": "Apoio estrutural",
      "summary": "Travessões e parênteses isolam ou destacam segmentos cuja função deve ser reconstruída, mas efeitos de voz, ênfase e comentário pertencem também ao discurso.",
      "editorialSourceId": "SUVECA-A08-G05",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "editorial_baseline_retained_after_review"
    },
    "A08/G06": {
      "level": "strong",
      "label": "Conexão forte",
      "summary": "Na revisão e reescrita, compare mapas antes e depois da pontuação para verificar correção, escopo e preservação ou alteração de sentido.",
      "editorialSourceId": "SUVECA-A08-G06",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A09/G01": {
      "level": "central",
      "label": "Método central",
      "summary": "A concordância verbal parte da seta entre Ve e o núcleo de Su, mesmo quando o sujeito está distante, posposto, oculto ou possui estrutura complexa.",
      "editorialSourceId": "SUVECA-A09-G01",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A09/G02": {
      "level": "central",
      "label": "Método central",
      "summary": "O aprofundamento testa sujeito oracional, expressões quantitativas, relativos e outros controladores sem se deixar enganar pela proximidade linear.",
      "editorialSourceId": "SUVECA-A09-G02",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A09/G03": {
      "level": "central",
      "label": "Método central",
      "summary": "Nas questões, localize o verbo, reconstrua o sujeito e seu núcleo e somente então aplique a regra geral ou o caso especial de concordância.",
      "editorialSourceId": "SUVECA-A09-G03",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A09/G04": {
      "level": "central",
      "label": "Método central",
      "summary": "Casos especiais são incorporados ao mapa como exceções controladas por estrutura, referente, porcentagem, pessoa, coordenação ou valor contextual.",
      "editorialSourceId": "SUVECA-A09-G04",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A09/G05": {
      "level": "central",
      "label": "Método central",
      "summary": "Na concordância nominal, conecte determinantes e qualificadores aos núcleos que controlam gênero e número, distinguindo adjunto e predicativo.",
      "editorialSourceId": "SUVECA-A09-G05",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "editorial_baseline_retained_after_review"
    },
    "A09/G06": {
      "level": "central",
      "label": "Método central",
      "summary": "Predicativos e particípios exigem setas para sujeito ou objeto; o mapa evita concordância mecânica com o termo mais próximo.",
      "editorialSourceId": "SUVECA-A09-G06",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "editorial_baseline_retained_after_review"
    },
    "A09/G07": {
      "level": "central",
      "label": "Método central",
      "summary": "Expressões especiais de concordância nominal são resolvidas depois de identificar classe, referente e função no sintagma ou na predicação.",
      "editorialSourceId": "SUVECA-A09-G07",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "editorial_baseline_retained_after_review"
    },
    "A09/G08": {
      "level": "central",
      "label": "Método central",
      "summary": "O fechamento integra classes variáveis e invariáveis à estrutura, mostrando quando uma forma concorda com um núcleo e quando modifica sem flexão.",
      "editorialSourceId": "SUVECA-A09-G08",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "editorial_baseline_retained_after_review"
    },
    "A10/G01": {
      "level": "central",
      "label": "Método central",
      "summary": "A regência verbal nasce da relação entre o sentido contextual de Ve e o C exigido, incluindo a preposição que realiza essa ligação.",
      "editorialSourceId": "SUVECA-A10-G01",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "editorial_baseline_retained_after_review"
    },
    "A10/G02": {
      "level": "central",
      "label": "Método central",
      "summary": "No aprofundamento, compare acepções do verbo e redes de complementos para evitar memorizar uma regência única fora do contexto.",
      "editorialSourceId": "SUVECA-A10-G02",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "editorial_baseline_retained_after_review"
    },
    "A10/G03": {
      "level": "central",
      "label": "Método central",
      "summary": "Com relativos, recoloque o antecedente na lacuna, identifique a regência dentro da subordinada e leve a preposição exigida para diante do pronome.",
      "editorialSourceId": "SUVECA-A10-G03",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A10/G04": {
      "level": "central",
      "label": "Método central",
      "summary": "A escolha entre pronomes pessoais decorre da função de complemento e da regência do verbo, não da posição ou da referência a pessoa.",
      "editorialSourceId": "SUVECA-A10-G04",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A10/G05": {
      "level": "central",
      "label": "Método central",
      "summary": "A regência nominal amplia C para completar substantivos, adjetivos e advérbios; o mapa explicita o núcleo regente e o termo preposicionado que o completa.",
      "editorialSourceId": "SUVECA-A10-G05",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "editorial_baseline_retained_after_review"
    },
    "A10/G06": {
      "level": "central",
      "label": "Método central",
      "summary": "A crase é verificada depois do mapa: primeiro confirme a exigência da preposição a pelo regente; depois teste se o termo seguinte admite artigo a.",
      "editorialSourceId": "SUVECA-A10-G06",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "editorial_baseline_retained_after_review"
    },
    "A10/G07": {
      "level": "central",
      "label": "Método central",
      "summary": "Casos proibidos, facultativos e questões de crase são resolvidos combinando regência, estrutura do termo seguinte, paralelismo e preservação de sentido.",
      "editorialSourceId": "SUVECA-A10-G07",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "editorial_baseline_retained_after_review"
    },
    "A11/G01": {
      "level": "support",
      "label": "Apoio estrutural",
      "summary": "A SuVeCA reconstrói participantes e relações locais; a coesão textual conecta esses mapas por retomadas, substituições, conectores e progressão.",
      "editorialSourceId": "SUVECA-A11-G01",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A11/G02": {
      "level": "strong",
      "label": "Conexão forte",
      "summary": "A coesão sequencial liga orações e períodos por relações lógicas; o mapa delimita as estruturas, e o conector mais o contexto determina a progressão.",
      "editorialSourceId": "SUVECA-A11-G02",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A11/G03": {
      "level": "strong",
      "label": "Conexão forte",
      "summary": "Na coesão referencial, a análise combina a função do termo na oração com o rastreamento anafórico, catafórico, dêitico ou lexical ao longo do texto.",
      "editorialSourceId": "SUVECA-A11-G03",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A12/G01": {
      "level": "indirect",
      "label": "Apoio indireto",
      "summary": "Sentido próprio e figurado dependem principalmente de contexto e interpretação semântica; a SuVeCA apenas localiza onde a transferência de sentido incide.",
      "editorialSourceId": "SUVECA-A12-G01",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A12/G02": {
      "level": "indirect",
      "label": "Apoio indireto",
      "summary": "Sinonímia e antonímia são relações lexicais e contextuais. O mapa pode controlar compatibilidade de função numa substituição, mas não estabelece equivalência de sentido.",
      "editorialSourceId": "SUVECA-A12-G02",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A12/G03": {
      "level": "strong",
      "label": "Conexão forte",
      "summary": "Hiperônimos e hipônimos podem construir coesão e referenciação entre orações; a SuVeCA localiza as funções, e a hierarquia lexical explica a retomada.",
      "editorialSourceId": "SUVECA-A12-G03",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "editorial_baseline_retained_after_review"
    },
    "A12/G04": {
      "level": "strong",
      "label": "Conexão forte",
      "summary": "Na polissemia de verbos, preposições e conectores, compare mapas e regências possíveis, mas use o contexto semântico para selecionar a acepção efetiva.",
      "editorialSourceId": "SUVECA-A12-G04",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "editorial_baseline_retained_after_review"
    },
    "A12/G05": {
      "level": "support",
      "label": "Apoio estrutural",
      "summary": "Ambiguidades estruturais podem ser representadas por mapas concorrentes; homônimos e parônimos, porém, exigem critérios lexicais e ortográficos próprios.",
      "editorialSourceId": "SUVECA-A12-G05",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "editorial_baseline_retained_after_review"
    },
    "A12/G06": {
      "level": "support",
      "label": "Apoio estrutural",
      "summary": "Elipse, zeugma, anacoluto, silepse, hipérbato e pleonasmo dialogam com a estrutura; metáfora, metonímia e outras figuras exigem também leitura semântica e discursiva.",
      "editorialSourceId": "SUVECA-A12-G06",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "editorial_baseline_retained_after_review"
    },
    "A12/G07": {
      "level": "indirect",
      "label": "Apoio indireto",
      "summary": "Figuras aprofundadas, ironia, eufemismo, hipérbole, sinestesia e efeitos sonoros são interpretados sobretudo no plano semântico-discursivo, com apoio sintático apenas pontual.",
      "editorialSourceId": "SUVECA-A12-G07",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "editorial_baseline_retained_after_review"
    },
    "A13/G01": {
      "level": "support",
      "label": "Apoio estrutural",
      "summary": "Na recorrência e na paráfrase, o mapa ajuda a verificar participantes, ações e relações preservadas; equivalência global ainda depende de contexto e escopo.",
      "editorialSourceId": "SUVECA-A13-G01",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A13/G02": {
      "level": "support",
      "label": "Apoio estrutural",
      "summary": "A inferência pode usar pistas de sujeito, verbo, negação, quantificação e circunstância, mas a conclusão emerge da articulação textual e do conhecimento autorizado pelo enunciado.",
      "editorialSourceId": "SUVECA-A13-G02",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A13/G03": {
      "level": "support",
      "label": "Apoio estrutural",
      "summary": "Na narração e descrição, a SuVeCA acompanha agentes, eventos, estados, tempos e circunstâncias; a tipologia resulta do funcionamento global do texto.",
      "editorialSourceId": "SUVECA-A13-G03",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A13/G04": {
      "level": "support",
      "label": "Apoio estrutural",
      "summary": "Mapear verbos, participantes e relações ajuda a comparar narração e exposição, sem substituir critérios de organização, finalidade e progressão textual.",
      "editorialSourceId": "SUVECA-A13-G04",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A13/G05": {
      "level": "support",
      "label": "Apoio estrutural",
      "summary": "Na exposição e argumentação, a SuVeCA esclarece proposições e conectores; tese, argumentos, modalização e estratégia discursiva pertencem à camada textual.",
      "editorialSourceId": "SUVECA-A13-G05",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A13/G06": {
      "level": "support",
      "label": "Apoio estrutural",
      "summary": "Questões variadas de interpretação usam o mapa para testar assertivas locais, escopo e relações lógicas, mas exigem sempre retorno ao texto completo.",
      "editorialSourceId": "SUVECA-A13-G06",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    },
    "A13/G07": {
      "level": "indirect",
      "label": "Apoio indireto",
      "summary": "Funções da linguagem são definidas por foco comunicativo, intenção e situação de uso; a SuVeCA pode analisar enunciados, mas não decide a função predominante.",
      "editorialSourceId": "SUVECA-A13-G07",
      "publicationStatus": "approved_with_constraints",
      "classificationReconciliation": "confirmed"
    }
  },
  "editorialConnectionSource": {
    "schemaVersion": "1.0.0",
    "sourceDigest": "1bb1af130fbe26418a6ba3fb28e4b1a387b97508b1377e76f7a809dad4e7e6ce",
    "policy": "A taxonomia humana do método prevalece sobre a classificação gerada. O Gemini fornece detalhamento e evidência; conflitos, riscos e experiências do app são filtrados antes da publicação.",
    "totals": {
      "approvedAppExperiences": {
        "analyzer": 59,
        "daily_review": 2,
        "decision_tree": 59,
        "error_notebook": 92,
        "flashcards": 102,
        "module": 102,
        "practice": 90,
        "professor": 12,
        "train_visualization": 54
      },
      "conflictsReviewed": 79,
      "connections": 102,
      "editorialRisksControlled": 303,
      "publicationStatuses": {
        "approved_with_constraints": 102
      },
      "reconciliations": {
        "confirmed": 61,
        "editorial_baseline_retained_after_review": 41
      },
      "reviewRecordsLinked": 82
    }
  }
} as const;
